spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twwedb
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # creates tables automatically
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
